
package com.sriox.vasatey.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Alert(
    // The ID is generated by the database, so it can be null when inserting
    val id: Int? = null, 

    @SerialName("guardian_email")
    val guardianEmail: String,

    @SerialName("from_user_name")
    val fromUserName: String,

    @SerialName("from_user_email")
    val fromUserEmail: String,

    @SerialName("from_user_mobile")
    val fromUserMobile: String?,

    val latitude: Double?,
    val longitude: Double?,

    // The timestamp is generated by the database, so it can be null when inserting
    @SerialName("created_at")
    val createdAt: String? = null 
)
